version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka/.
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - ./mount/prometheus:/etc/prometheus
    links:
      - kafka
  linewebhook:
    build: line_webhook/.
    links: 
      - kafka
    ports:
      - "8080:8080"
    environment:
      CHANNEL_SECRET: <your secret> 
      CHANNEL_ACCESS_TOKEN: <your access token> 
      BOOTSTRAP_SERVERS: kafka:9092
      TOPIC_IMCOMING: line_imcoming
      TOPIC_OUTGOING: line_outgoing
  botconnect:
    build: bot_connect/.
    links: 
      - kafka
    ports:
      - "8082:8082"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      TOPIC_IMCOMING: line_imcoming
      TOPIC_OUTGOING: line_outgoing